spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: C:\Project Streamer Config
          search-paths: '{application}'
          defaultLabel: master
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"

