server:
  port: 8091
spring:
  application:
    name: movies-service
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost