spring:
  cloud:
    gateway:
      routes:
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies-service/**
          filters:
            - AuthenticationFilter
        - id: tv-shows-service
          uri: lb://TV-SHOWS-SERVICE
          predicates:
            - Path=/tv-shows-service/**
          filters:
            - AuthenticationFilter
        - id: watchlist-service
          uri: lb://WATCHLIST-SERVICE
          predicates:
            - Path=/watchlist-service/**
          filters:
            - AuthenticationFilter
  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/