server:
  port: 8092
spring:
  application:
    name: watchlist-service
  profiles:
    active: ${activatedProperties:dev}
  config:
    import: optional:configserver:${configUri:http://localhost:8888/}